/*
-- Query: SELECT * FROM music_electric.products
LIMIT 0, 1000

-- Date: 2015-10-25 16:14
*/

use music_electric;

INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (1,1,'Fender American Stratocaster','This is a strat',1299.99,'images/guitars/strat.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (2,1,'Gibson Custom Shop VOS ES-335','Gibson',3199.99,'images/guitars/Gibson_ES335.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (3,1,'Rickenbacker 330 Fireglo','Rickenbacker',3499.99,'images/guitars/rick.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (4,1,'ESP LTD EC-1000','ESP LTD',599.99,'images/guitars/ltdec1000.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (5,2,'Taylor','Acoustic',619.99,'images/guitars/Taylor.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (6,2,'Yamaha F-335 Acoustic','Acoustic Guitar',129.99,'images/guitars/YamahaF335.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (7,3,'Ibanez SRFF806','Six-String Electric Bass Guitar Black Stained',1059.99,'images/guitars/Ibanez_bass.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (8,3,'Fender Deluxe J-Bass','Sea Foam Pearl',699.99,'images/guitars/Fender_deluxe.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (9,9,'Eastman A-Style Mandolin',' \"All Solid Maple Back & Sides - Solid Spruce Top - Geared tuning pegs - Stamped Eastman Tailpiece - Classic Matte finish\"',699.99,' images/guitars/eastmanMandolin.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (10,9,'Uke - Hawaiian',' \"Beginner uke - Soprano\"',99.99,' images/guitars/uke.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (11,8,'Ludwig Junior Drum Kit Outfit','<ul>\n	<li>Bass drum(s): 16\" x 10\"</li>\n	<li>Tom(s): 8\" x 5\", 10\" x 5\"</li>\n	<li>Floor tom(s): 13\" x 10\"</li>\n	<li>Snare: 12\" x 4\"</li>\n	<li>Total pieces: 5</li>\n	<li>Bass drum(s): 16\" x 10\"</li>\n	<li>Tom(s): 8\" x 5\", 10\" x 5\"</li>\n	<li>Floor tom(s): 13\" x 10\"</li>\n	<li>Snare: 12\" x 4\"</li>\n	<li>Total pieces: 5</li>\n</ul><br />\n	<p>EXTRAS:</p>\n<ul>\n	<li>Cymbals: Yes</li>\n	<li>Total cymbals: 2</li>\n	<li>Hardware: Yes</li>\n	<li>Bass pedal(s): Yes</li>\n	<li>Hi-hat stand: Yes</li>\n</ul>',449.99,'images/drums/Ludwig.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (12,8,'Yamaha Stage Custom 5 Piece Drum Kit','   <ul> 				       <li>Birch Shell Bass drum 7-ply, 7mm</li> 				       <li>Birch toms, floor tom, snare 6-ply, 6mm</li> 				       <li>Absolute-style lugs low mass lugs</li> 				       <li>Air Seal System shells</li> 				       <li>45-Degree bearing edg...',699.99,'images/drums/YamahaStage.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (13,7,'Yamaha DTX 450K Electric Drum Kit','<ul>\n					   <li>20 x 17\" bass</li>\n				       <li>10 x 7\", and 12 x 8\" mounted toms</li>\n				       <li>14 x 13\" floor tom drum</li>\n				       <li>14 x 5-1/2\" snare drum (10-lug)</li>\n				       <li>Total pieces: 5</li>\n	              </ul>',1499.99,'images/drums/Yamaha.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (14,7,'Roland TD-30K Electric Drum Kit',' <ul>\n				       <li>Bass drum(s): 16\" x 10\"</li>\n				       <li>Tom(s): 8\" x 5\", 10\" x 5\"</li>\n				       <li>Floor tom(s): 13\" x 10\"</li>\n				       <li>Snare: 12\" x 4\"</li>\n				       <li>Total pieces: 5</li>\n					   <li>Bass drum(s): 16\" x 10\"</li>\n				       <li>Tom(s): 8\" x 5\", 10\" x 5\"</li>\n				       <li>Floor tom(s): 13\" x 10\"</li>\n				       <li>Snare: 12\" x 4\"</li>\n				       <li>Total pieces: 5</li>\n					   \n	              </ul>',4999.99,'images/drums/Roland-TD-30K.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (15,4,'Marshall 1962 Reissue Bluesbreaker','<ul>\n						<li>30W output</li>\n						<li>2 - 12\" 25W Celestion Greenback speakers</li>\n						<li>Valve rectifier</li>\n					</ul>',1399.99,'images/amplifiers/Marshall_bluesbreaker.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (16,4,'Fender Super Sonic 22 Watt 1x12\" Combo','<ul>\n					<li>Deluxe Reverb power platform</li>\n					<li>Vintage channel contains pre-gain tone controls and two switchable voices</li>\n					<li>Burn channel contains dual gain controls and post-gain EQ</li>\n					<li>Fender long-spring Reverb by Accutronics</li>\n					<li>Ivory \"radio\" knobs</li>\n					<li>4-button footswitch for Channel, Fat, Reverb, Effects Loop</li>\n					<li>Amp Type: Tube</li>\n					<li>Output: 22 Watts, 8 ohms</li>\n					<li>Speaker: 12\", 50 Watt Fender \"Lightning Bolt\" Speaker by Eminence</li>\n					<li>Channels: 2 (Vintage and Burn)</li>\n					<li>Controls: Vintage Channel: Volume, Treble, Bass, Voicing Switch (Normal/Fat) <br/> Channel: Gain 1, Gain 2, Treble, Bass, Middle, Volume, Master Reverb</li>\n					<li>Effects Spring Reverb</li>\n				</ul>',1049.99,'images/amplifiers/Fender_SuperSonic.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (17,5,'Fender Acoustasonic 90 1x8\" 90-Watt Acoustic Combo with Horn','90W, 2-channel Acoustic Amplifier with, Effects, <br /> Feedback Elimination, and Balanced Line Out',299.99,'images/amplifiers/FenderAcous60Amp.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (18,6,'Gallien-Krueger MB112-II 1x12\" 200-Watt Bass Combo','200W 1 x 12\" Bass Combo Amp with Digital Power Amp, 4-band Active EQ, <br /> Aux in, XLR Direct Out, and Chain Out',399.99,'images/amplifiers/GKmb112.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (19,6,'Ampeg BA-210v2 - 2x10\" 450-Watt Bass Combo with Scrambler','450W 2 x 10\" Bass Combo Amplifier with 3-band EQ, Aux Input, <br />15dB Pad, Headphone Output, Ultra Hi/Lo Tone Shaping, Effects Loop, <br /> Direct out, High Frequency Mute, and Bass Scrambler - Black',499,'images/amplifiers/ba210.jpg');
INSERT INTO `products` (`prod_id`,`cat_id`,`title`,`descr`,`price`,`photo_loc`) VALUES (20,5,'Fishman Loudbox Artist 120-Watt Acoustic Amp','120-Watt Acoustic Guitar Amp',549,'images/amplifiers/fishmanLoudbox.jpg');
